import type { NextPage } from "next";
import Head from "next/head";
import { Suspense } from "react";
import styles from "../styles/Home.module.css";
import delay from "delay";

const delaySuspense = (() => {
  let pending = true;
  return () => {
    if (pending) {
      throw delay(5000).then(() => (pending = false));
    }
  };
})();

const SlowComponent = () => {
  delaySuspense();

  return <div>Thanks for waiting</div>;
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Suspense fallback={<div>Loading...</div>}>
          <SlowComponent />
        </Suspense>
      </main>
    </div>
  );
};

export default Home;
